# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-30 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SharesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='分类ID')),
                ('industry', models.CharField(max_length=128, verbose_name='所属行业')),
                ('industryClassification', models.CharField(max_length=128, verbose_name='所属行业类别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票分类',
                'verbose_name_plural': '股票分类',
                'db_table': 'shares_category',
                'ordering': ['-created_at'],
            },
        ),
    ]
