# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-08-30 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_auto_20200830_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharescategory',
            name='count',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
