# Generated by Django 3.1.1 on 2020-09-02 06:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0003_sharescategory_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.UUID('748041b0-65ae-464a-b9a0-acd8a8ae16ee'), verbose_name='股票ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='股票代码')),
                ('code_name', models.CharField(max_length=32, unique=True, verbose_name='股票名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
                'db_table': 'shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
