# Generated by Django 3.1.1 on 2020-09-02 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0004_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='industry',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('da88cfe0-77b6-422f-8b9c-de056f551c93'), verbose_name='股票ID'),
        ),
    ]
