# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-09-02 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_auto_20200902_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0dbf6cce-a7ee-43a3-b270-b355fc467e05'), verbose_name='股票ID'),
        ),
    ]
