# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-09-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0009_auto_20200902_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0b10fc2b-a9b6-47af-a555-1690bfaf2893'), verbose_name='股票ID'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='close',
            field=models.CharField(max_length=128, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='open',
            field=models.CharField(max_length=128, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='pctChg',
            field=models.CharField(max_length=1280, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='peTTM',
            field=models.CharField(max_length=128, verbose_name='滚动市盈率'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='turn',
            field=models.CharField(max_length=128, verbose_name='换手率'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='volume',
            field=models.CharField(max_length=128, verbose_name='成交量'),
        ),
    ]
