# Generated by Django 3.1.1 on 2020-09-03 00:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0011_auto_20200903_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('034e47d2-edb0-4a00-a483-02ace5308b95'), verbose_name='股票ID'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='code',
            field=models.CharField(max_length=32, verbose_name='股票代码'),
        ),
    ]
