# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-09-06 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0014_auto_20200903_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesdetail',
            name='high',
            field=models.CharField(default=0, max_length=128, verbose_name='最高价'),
        ),
        migrations.AddField(
            model_name='sharesdetail',
            name='isST',
            field=models.SmallIntegerField(default=0, verbose_name='是否ST股'),
        ),
        migrations.AddField(
            model_name='sharesdetail',
            name='low',
            field=models.CharField(default=0, max_length=128, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('0a17aea7-2dcb-4745-bb74-8904ac4aa010'), verbose_name='股票ID'),
        ),
    ]
