# Generated by Django 3.1.1 on 2020-09-08 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0015_auto_20200906_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f71f32e1-c814-453e-aeca-9212a893403e'), verbose_name='股票ID'),
        ),
    ]
