# Generated by Django 3.1.1 on 2020-09-08 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0016_auto_20200908_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharesdetail',
            name='adjustflag',
            field=models.SmallIntegerField(default=3, verbose_name='复权状态'),
        ),
        migrations.AddField(
            model_name='sharesdetail',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='成交量'),
        ),
        migrations.AddField(
            model_name='sharesdetail',
            name='pbMRQ',
            field=models.CharField(default=0, max_length=128, verbose_name='市净率'),
        ),
        migrations.AddField(
            model_name='sharesdetail',
            name='pcfNcfTTM',
            field=models.CharField(default=0, max_length=128, verbose_name='滚动市现率'),
        ),
        migrations.AddField(
            model_name='sharesdetail',
            name='preclose',
            field=models.CharField(default=0, max_length=128, verbose_name='前收盘价'),
        ),
        migrations.AddField(
            model_name='sharesdetail',
            name='psTTM',
            field=models.CharField(default=0, max_length=128, verbose_name='滚动市销率'),
        ),
        migrations.AddField(
            model_name='sharesdetail',
            name='tradestatus',
            field=models.SmallIntegerField(default=1, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c8975fa7-bc95-4742-bba3-dd51e92d7aa0'), verbose_name='股票ID'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='pctChg',
            field=models.CharField(max_length=128, verbose_name='涨跌幅'),
        ),
    ]
