# Generated by Django 3.1.1 on 2020-09-08 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0017_auto_20200908_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('fbf29cb3-571a-447a-8620-76c29360a9e6'), verbose_name='股票ID'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='amount',
            field=models.FloatField(default=0, verbose_name='成交量'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='close',
            field=models.FloatField(max_length=128, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='high',
            field=models.FloatField(default=0, max_length=128, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='low',
            field=models.FloatField(default=0, max_length=128, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='open',
            field=models.FloatField(max_length=128, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='pbMRQ',
            field=models.FloatField(default=0, max_length=128, verbose_name='市净率'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='pcfNcfTTM',
            field=models.FloatField(default=0, max_length=128, verbose_name='滚动市现率'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='pctChg',
            field=models.FloatField(max_length=128, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='peTTM',
            field=models.FloatField(max_length=128, verbose_name='滚动市盈率'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='preclose',
            field=models.FloatField(default=0, max_length=128, verbose_name='前收盘价'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='psTTM',
            field=models.FloatField(default=0, max_length=128, verbose_name='滚动市销率'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='turn',
            field=models.FloatField(max_length=128, verbose_name='换手率'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='volume',
            field=models.FloatField(max_length=128, verbose_name='成交量'),
        ),
    ]
