# Generated by Django 3.1.1 on 2020-09-08 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0018_auto_20200908_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('780eda1b-3945-4249-941f-ff16ffccae81'), verbose_name='股票ID'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='close',
            field=models.FloatField(default=0, max_length=128, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='open',
            field=models.FloatField(default=0, max_length=128, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='pctChg',
            field=models.FloatField(default=0, max_length=128, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='peTTM',
            field=models.FloatField(default=0, max_length=128, verbose_name='滚动市盈率'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='turn',
            field=models.FloatField(default=0, max_length=128, verbose_name='换手率'),
        ),
        migrations.AlterField(
            model_name='sharesdetail',
            name='volume',
            field=models.FloatField(default=0, max_length=128, verbose_name='成交量'),
        ),
    ]
