# Generated by Django 3.1.1 on 2020-09-08 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0020_auto_20200908_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharesdetail',
            options={'ordering': ['-date'], 'verbose_name': '股票详情', 'verbose_name_plural': '股票详情'},
        ),
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('304d4b36-edfc-44e0-b4e9-043c8e5914b4'), verbose_name='股票ID'),
        ),
    ]
