# Generated by Django 3.1.1 on 2020-09-27 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0021_auto_20200908_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f6a997fc-8a0a-4276-ae39-de132f3739d4'), verbose_name='股票ID'),
        ),
    ]
