# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-09-13 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0021_auto_20200908_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shares',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4a51d0a6-0e1c-453f-a877-1f3bb6a6fb31'), verbose_name='股票ID'),
        ),
    ]
